services:
  - type: web
    name: flutter-cn-demo-preview
    runtime: static
    buildCommand: bash tool/build-render.sh
    staticPublishPath: _site
    previews:
      generation: automatic
    envVars:
      - key: NODE_VERSION
        value: "22"
        previewValue: "22"
      - key: PRODUCTION
        value: "true"
        previewValue: "false"
      - key: OPTIMIZE
        value: "true"
        previewValue: "true"
    branch: main
